
language: ruby
rvm:
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree
before_script:
  - mysql -u root -e 'create database cs188_test;'
script: bundle exec rspec spec